### PR TITLE
Initial single header support using amalgamate

### PR DESCRIPTION
**Pull request by patrick--**
This PR was to make progress in regards to #23. I've only used amalgamate a handful of times on small personal projects - so feel free to correct or advise on any specifics on it's use in this project. 

Invoking the script is as simple as `python amalgamate.py -c config.json -s ../include`

To verify I simply tested the single header file against `example.cpp` and the `test.cpp`.

Thanks! 

Fixes: #23

### CODE REVIEW

**Comment by mandreyel** [comment]
@patrick-- Thank you so much! I am a little snowed under but will have time to look at it in the coming days :)

**Comment by mandreyel** [comment]
@patrick--  Alright, had time to check it, looks great :)

One thing. Could you also update the README to mention that there is a single header option now?

**Comment by patrick--** [comment]
@mandreyel Thank you for the quick feedback. I've updated the README. Let me know if it sounds okay!

**Comment by mandreyel** [comment]
@patrick-- Great work! Thank __you__ :)

**Pull request merged**
