### PR TITLE
Travis, CDash, and CMake 3.14 warnings

### PR DESCRIPTION
**Pull request by apmccartney**
Hello @mandreyel !

I've encountered a few minor bumps regarding mio's CMake build system, and took the opportunity to make some minor improvements and add continuous testing and monitoring.

This pull request:
+ Modifies the convention for mio::mio and the windows api (in a backwards compatible way) to facilitate decision deferral.
+ Addresses relative path warning in CMake 3.14
+ Added TravisCI support to the repository
+ Adds CDash-integration

### CODE REVIEW

**Comment by apmccartney** [comment]
In order to take advantage of the TravisCI- and CDash-integration, you'll need to configure a Travis-CI instance, which is

1. free for open source projects like mio
1. relatively painless to stand up, in my experience

If you're unfamiliar, Travis is a continuous Integration service with tight coupling to Github. Once configured, each time you push to your Github repository, Travis is notified and will build and test that commit of the repository. I currently have Travis-CI configured for my fork. You can see what that looks like [here](https://travis-ci.com/apmccartney/mio).

CDash is a component of the CMake ecosystem which aggregates, analyzes, and displays the results of software testing processes submitted from clients. Typically, you'd stand up a server to host a CDash instance, but Kitware hosts a [public server](https://my.cdash.org/viewProjects.php) for open source projects. I've set up a [mio project](https://my.cdash.org/index.php?project=mio) there and each test run by Travis-CI will report there.

The killer feature, in my opinion, is the [coverage report](https://my.cdash.org/viewCoverage.php?buildid=1658533&filtercount=1&field1=filename/string&compare1=63&value1=&status=6), which can show the line by line coverage of your source files ([example](https://my.cdash.org/viewCoverageFile.php?buildid=1658533&fileid=2569855))

**Comment by mandreyel** [comment]
Good to see you again, @apmccartney! I appreciate the effort that went into this. I will have time this weekend to set up TravisCI and properly look at this PR.

**Comment by apmccartney** [comment]
Hey @mandreyel. Anything I can do to help? Have you run into any issues setting up CI?

**Comment by apmccartney** [comment]
Hey @mandreyel. Just checking in. I figure life is busy for you right now. Hope all is well.

**Comment by apmccartney** [comment]
poke

**Comment by mandreyel** [comment]
@apmccartney I have completely forgotten this, I am so sorry! You're right, without going into detail, life has been extremely busy in the past two months, but things seem to be settling down. I appreciate your concern very much :)

I know I said this before, but this weekend I should definitely have time. Bear with me!

**Comment by apmccartney** [comment]
I totally understand. I hope it's been a good busy!

If there's anything I can do to help, please don't hesitate to to let me know.

**Comment by apmccartney** [comment]
Checking in

**Comment by mandreyel** [comment]
@apmccartney Well, nothing goes as planned. My sincere apologies, I hope you do not feel that I am not appreciating your work, this is the first free weekend I had in months.

I looked into your work and I must say your level of CMake is so far beyond mine that I am trusting your judgement with these changes. I also set up my account on TravisCI, it will be very useful for this project :)

Thank you for your work and patience! I hope to be more active in open source going forward.

**Pull request merged**
