### PR TITLE
Expanded CMake Support

### PR DESCRIPTION
**Pull request by apmccartney**
This commit introduces several features for the CMake build system.

+ CTest integration
+ CDash integration
+ CPack integration
+ CMake find_package support

To accomodate post-installation consumption, the `include` preprocessor
statements in several library header files were updated to use paths
relative to a root include directory rather than paths relative to the
file itself.

### CODE REVIEW

**Comment by apmccartney** [comment]
Closes #11

**Comment by mandreyel** [comment]
@apmccartney Thank you so much for this! I will have time to look at this in more detail tomorrow or the day after at the latest, but it looks promising.

**Comment by mandreyel** [comment]
@apmccartney So I had some time to look through the changes and try it. I cloned your repo and tried `mkdir build && cd build` then `cmake ..` and it failed with:
```
CMake Error at CMakeLists.txt:65 (add_subdirectory):
  The source directory

    /tmp/mio/test

  does not contain a CMakeLists.txt file.
```
However, I'm not very good at CMake so it could be that I missed something. Would you be willing to extend the readme to include usage instructions for CMake noobs like myself? I'm thinking of both usage as a library from within another project (i.e. with find_package), as well as just installing it on the system for other projects to use.

**Comment by apmccartney** [comment]
Whoops! I apologize. 
I forgot to commit and push `CMakeLists.txt` file for that directory. At work at the moment but I'll push the file in ~30 minutes

**Comment by apmccartney** [comment]
The missing file has been committed and pushed. I made a small change to the `.gitignore` to allow git to track the file going forward as well.

**Comment by apmccartney** [comment]
> Would you be willing to extend the readme to include usage instructions for CMake noobs like myself? I'm thinking of both usage as a library from within another project (i.e. with find_package), as well as just installing it on the system for other projects to use.

Sure! I'll add that content sometime this evening.

**Comment by mandreyel** [comment]
@apmccartney Awesome, it works as expected now. And sure, at your earliest convenience. Much appreciated!

**Comment by mandreyel** [comment]
@apmccartney This is exceptional work! Not only did this turn mio into a more complete library, it also taught me a great deal about CMake. Thank you so much!

**Pull request merged**
